apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
     name: comments
     labels:
       app: comments
       tier: backend
    spec:
     containers:
     - name: comments
       image: alazidis/blog-microservices-comments
       ports:
         - containerPort: 5000
       env:
         - name: COMMENT_PORT
           valueFrom:
             configMapKeyRef:
               key: COMMENT_PORT
               name: blog-microservices
         - name: COMMENT_TOPIC
           valueFrom:
            configMapKeyRef:
               key: COMMENT_TOPIC
               name: blog-microservices
         - name: KAFKA_BROKERS
           valueFrom:
            configMapKeyRef:
             key: KAFKA_BROKERS
             name: blog-microservices

