apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-depl
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
        tier: dashboard
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:1.0.0-alpha.4
        ports:
        - containerPort: 8081
        env:
         - name: ME_CONFIG_MONGODB_ADMINUSERNAME
           valueFrom:
             secretKeyRef:
              key: MONGO_USERNAME
              name: secret-db
         - name: ME_CONFIG_MONGODB_ADMINPASSWORD
           valueFrom:
             secretKeyRef:
              key: MONGO_PASSWORD
              name: secret-db
         - name: ME_CONFIG_BASICAUTH_USERNAME
           valueFrom:
             secretKeyRef:
              key: ME_CONFIG_BASICAUTH_USERNAME
              name: secret-db
         - name: ME_CONFIG_BASICAUTH_PASSWORD
           valueFrom:
             secretKeyRef:
              key: ME_CONFIG_BASICAUTH_PASSWORD
              name: secret-db
         - name: ME_CONFIG_MONGODB_SERVER
           valueFrom:
            configMapKeyRef:
             name: blog-microservices
             key: MONGO_HOST
