apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-depl
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        tier: database
    spec:
      containers:
      - name: mongo
        image: mongo:4.2.24
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db 
        env:
         - name: MONGO_INITDB_ROOT_USERNAME
           valueFrom:
             secretKeyRef:
               name: secret-db
               key: MONGO_USERNAME
         - name: MONGO_INITDB_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: secret-db
               key: MONGO_PASSWORD
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
