apiVersion: v1
kind: Service
metadata:
  name: query-comments-post-svc
spec:
  selector:
    app: query-comments-post
  ports:
  - name: query-comments-post
    protocol: TCP
    port: 6000
    targetPort: 6000
