credentials_gcp = "/home/apostolos/Desktop/Terraform/kubernetes-cluster/credentials"
project-id      = "lively-shelter-294615"
region          = "europe-west3"
zone            = "europe-west3-c"
vpc-name        = "vpc-multicluster"
google_eshop_ns = ""
